ITEM_NAME_TO_ID = {
    "Blaster": 1,
    "Skirmish": 2,
    "Firefight": 3,
    "Aftershock": 4,
    "Sparkjump": 5,
    "Jumpstart": 6,
    "Overwatch": 7,
    "Aurora": 8,
    "Corona": 9,
    #"UltimatePrimary": 10,
    "Flashbang": 11,
    "Hailstorm": 12,
    "Knockdown": 15,
    "Airburst": 16,
    "Slapshot": 17,
    "Lock-on": 18,
    "Watchdog": 19,
    "Claymore": 20,
    "Lookout": 21,
    "Twister": 22,
    #"UltimateR1": 23,
    "Shockpunch": 24,
    "Slipstream": 25,
    #"UltimateGlide": 26,
    "Discord": 27,
    "Safeguard": 28,
    "Bulletproof": 29,
    "Stronghold": 30,
    "Highgear": 31,
    "Smackdown": 33,
    "Shieldwall": 34,
    "Hawkeye": 35,
    "Deflector": 36,
    "Fullspeed": 37,
    "Pressurepoint": 38,
    "Shepherd": 39,
    "Rangefinder": 40,
    "Kickback": 41,
    "Covert": 42,
    "Tractor": 43,
    #"UltimateShield": 44,
    "Buildup": 45,
    "Comeback": 46,
    "Highjump": 47,
    "Failsafe": 48,
    
    #Adding 50 for the Datacons, not sure if this order is correct or not, but what I am doing for now
    "Datacon (None)": 51,
    "Datacon (CharacterEnergon)": 52,
    "Datacon (RendersAutobots2)": 53,
    "Datacon (CardArtwork)": 54,
    "Datacon (DecepticloneSubmission)": 55,
    "Datacon (LeClezio1)": 56,
    "Datacon (RendersDecepticons2)": 57,
    "Datacon (ConceptArtDecepticlone)": 58,
    "Datacon (LeClezio2)": 59,
    "Datacon (TVSeriesThemeMusic)": 60,
    "Datacon (LevelStoryboardsAmazon)": 61,
    "Datacon (ArtPostcards)": 62,
    "Datacon (InstructionSheetOptimus)": 63,
    "Datacon (ConceptArtAutobots)": 64,
    "Datacon (MovieStills6)": 65,
    "Datacon (MovieStills7)": 66,
    "Datacon (RendersDecepticon)": 67,
    "Datacon (ThemeRegurgitator)": 68,
    "Datacon (MiniComic1)": 69,
    "Datacon (MiniComic2)": 70,
    "Datacon (MiniComic3)": 71,
    "Datacon (MiniComic4)": 72,
    "Datacon (ProductionArtAmazon)": 73,
    "Datacon (ProductionArtAntarctica)": 74,
    "Datacon (ProductionArtDeepAmazon)": 75,
    "Datacon (ProductionArtMidAtlantic)": 76,
    "Datacon (ProductionArtAlaska)": 77,
    "Datacon (ProductionArtStarship)": 78,
    "Datacon (ProdcutionArtPacificIsland)": 79,
    "Datacon (ProductionArtAutobotHQ)": 80,
    "Datacon (RendersAutobots)": 81,
    "Datacon (RendersDecepticlone)": 82,
    "Datacon (RendersMiniCons)": 83,
    "Datacon (ToyProductionHotShot)": 84,
    "Datacon (ToyProductionOptimus)": 85,
    "Datacon (ToyProductionRedAlert)": 86,
    "Datacon (ToyProductionMinicons)": 87,
    "Datacon (ToyProductionCyclonus)": 88,
    "Datacon (ToyProductionStarscream)": 89,
    "Datacon (ToyProductionTidalWave)": 90,
    "Datacon (ToyProductionMegatron)": 91,
    "Datacon (RendersAutobots3)": 92,
    "Datacon (CGProductionSequence2)": 93,
    "Datacon (CGProductionSequence)": 94,
    "Datacon (InstructionSheetMegatron)": 95,
    "Datacon (InstructionSheetHotShot)": 96,
    "Datacon (RendersDecepticlone2)": 97,
    "Datacon (RendersDecepticlone3)": 98,
    "Datacon (RendersDecepticlone4)": 99,
    "Datacon (TVSpot1)": 100,
    "Datacon (TVSpot2)": 101,
    "Datacon (TVSpot3)": 102,
    "Datacon (TVSpot4)": 103,
    "Datacon (TVSpot5)": 104,
    "Datacon (InstructionSheetRedAlert)": 105,
    "Datacon (MovieStills1)": 106,
    "Datacon (MovieStills2)": 107,
    "Datacon (MovieStills3)": 108,
    "Datacon (MovieStills4)": 109,
    "Datacon (MovieStills5)": 110,
    "Datacon (Dropbox_Wishbone)": 111,
    "Datacon (ThemeDropbox)": 112,
    "Datacon (LaunchPhotos)": 113,
    "Datacon (ThemeOrchestral)": 114,
    
    #saw this on the pickup list, I assume this is the powerlink
    #"Melee Damage Enhance": 150,
    
    #adding this per a requirement in the world.py
    "Health Drop": 151,
    "Big Head (2min)": 152,
    "Stealth Trap": 153,
    
}



# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.

#location ids are ID+1
LOCATION_NAME_TO_ID = {
    "Amazon-Claymore Cave": 1,
    "Amazon-Spire": 3,
    "Amazon-Neighboring Mountain": 5,
    "Amazon-Ravine Cliff Cave": 6,
    "Amazon-Pressurepoint's Corner": 7,
    "Amazon-Foot of the Mountain": 8,
    "Amazon-Mountain Ruins": 9,
    "Amazon-Before the Waterfall Bridge": 10,
    "Amazon-Spidertank Triplets": 12,
    "Amazon-Ruined Temple Alcove": 13,
    "Amazon-Forest before the Bridge": 14,
    "Amazon-Ruined Temple Ledge": 16,
    "Amazon-Forest before Firefight": 17,
    "Amazon-Tutorial Minicon": 18,
    "Amazon-Ruined Temple Courtyard": 19,
    "Amazon-Light Unit Party": 20,
    "Amazon-Hidden Cave": 21,
    "Amazon-Riverside Ledge": 22,
    "Amazon-Waterfall Base": 23,
    "Amazon-Forest after the Bridge": 24,
    "Amazon-Surprise": 25,
    "Amazon-Forgettable Location": 26,
    "Amazon-Medium Unit Party": 27,
    "Amazon-Forest Across from the Basin 1": 28,
    "Amazon-Forest Across from the Basin 2": 29,
    "Antartica-Rock of Power": 31,
    "Antartica-Research Base Office 1": 35,
    "Antartica-Midfield Beacon": 38,
    "Antartica-Hide-and-Seek Champion": 39,
    "Antartica-Research Base Containers 1": 40,
    "Antartica-Research Base Containers 2": 41,
    "Antartica-Research Base Office 3": 42,
    "Antartica-Crashed Icebreaker": 45,
    "Antartica-Research Center Hangar": 46,
    "Antartica-Beachfront Property": 47,
    "Antartica-Crashed Plane": 48,
    "Antartica-Research Base Office 4": 49,
    "Antartica-Crevasse Field Overlook": 50,
    "Antartica-Lonely Island": 51,
    "Antartica-Research Base Office 2": 52,
    "Antartica-Across the Field": 53,
    "Deep Amazon-Island Altar": 54,
    "Deep Amazon-Top of the Temple": 56,
    "Deep Amazon-Spawn Ledge": 58,
    "Deep Amazon-Waterfall Rock": 59,
    "Deep Amazon-Jungle Ruins": 60,
    "Deep Amazon-Patrolling Dropship": 61,
    "Deep Amazon-Jungle Village Outskirts": 62,
    "Deep Amazon-Field before the Bridge": 63,
    "Deep Amazon-Temple Climb": 65,
    "Deep Amazon-Mid-Jungle Ditch": 66,
    "Deep Amazon-Village at the Foot of the Hill": 67,
    "Deep Amazon-Jungle Village Warpgate": 68,
    "Deep Amazon-Temple Dead End": 69,
    "Deep Amazon-Temple Pool": 70,
    "Deep Amazon-Temple Side-Path": 71,
    "Deep Amazon-Forest before the Bridge": 72,
    "Deep Amazon-Antechamber": 73,
    "Deep Amazon-Antechamber Alcove": 74,
    "Deep Amazon-Behind the Temple": 75,
    "Mid Atlantic-Vanilla Progression": 76,
    "Mid Atlantic-Distant Island": 77,
    "Mid Atlantic-Pinnacle Rock": 78,
    "Mid Atlantic-Atoll": 79,
    "Alaska-Mountaintop": 84,
    "Alaska-Small Forest": 85,
    "Alaska-Cave's Far Ledge": 87,
    "Alaska-Cave's Right Fork": 88,
    "Alaska-Cave's Left Fork": 89,
    "Alaska-Cave's Pool": 90,
    "Alaska-Along the Canyon": 91,
    "Alaska-Ocean Overlook": 92,
    "Alaska-Hidden Hill": 94,
    "Alaska-Canyon Clearing Ledge 1": 95,
    "Alaska-Battlefield": 96,
    "Alaska-Canyon Clearing Ledge 2": 97,
    "Alaska-Dropship Island": 98,
    "Alaska-Peninsula": 99,
    "Alaska-Escape": 100,
    "Alaska-Hillside": 101,
    "Starship-Start of the Climb": 102,
    "Starship-First Steps": 103,
    "Starship-Main Elevator": 104,
    "Starship-Sideways Elevator": 105,
    "Starship-Lower Dropship": 106,
    "Starship-Bait": 107,
    "Starship-Free Space": 108,
    "Starship-Across the Gap": 109,
    "Starship-Early Gift": 110,
    "Starship-Bridge": 111,
    "Starship-Top of the Crashed Ship": 113,
    "Starship-Dropdown 1": 114,
    "Starship-Risky Jump": 115,
    "Starship-Rock 1": 116,
    "Starship-Middle Dropship": 117,
    "Starship-Dropdown 2": 118,
    "Starship-Rock 2": 119,
    "Starship-Rock 3": 120,
    "Starship-Rock 4": 121,
    "Pacific Island-Small Silo": 123,
    "Pacific Island-Moai": 124,
    "Pacific Island-Back of the Volcano": 125,
    "Pacific Island-Volcano Path": 126,
    "Pacific Island-Lighthouse": 128,
    "Pacific Island-Waterfall Climb": 129,
    "Pacific Island-Stronghold Ledge": 130,
    "Pacific Island-High Volcano Ledge": 132,
    "Pacific Island-Forest Basin": 133,
    "Pacific Island-Hidden Ledge": 134,
    "Pacific Island-Above the Waterfall": 135,
    "Pacific Island-Large Silo": 136,
    "Pacific Island-Small Island": 137,
    "Pacific Island-Bunker 1": 138,
    "Pacific Island-Bunker 4": 141,
    "Pacific Island-Bunker 5": 142,
    "Pacific Island-Bunker 6": 143,
    "Pacific Island-Bunker 7": 144,
    "Pacific Island-Bunker 8": 145,
    "Pacific Island-Bunker 9": 146,
    "Pacific Island-Bunker 2": 147,
    "Pacific Island-Bunker 3": 148,
    "Amazon-Beginner Weapon": 42069
}


#Original location (name) : linked location's ID
Linked_Locations{
    "Mid Atlantic-Vanilla Progression": 80,
    "Mid Atlantic-Distant Island": 81,
    "Mid Atlantic-Pinnacle Rock": 83,
    "Mid Atlantic-Atoll": 82,
    "Starship-Bridge": 112,
}


#adds 3 when outputing the file, so minicon ID is actually 16
Archipelago_Item_ID = 13