ITEM_NAME_TO_ID: dict[str,int] = {
    "Blaster": 1,
    "Skirmish": 2,
    "Firefight": 3,
    "Aftershock": 4,
    "Sparkjump": 5,
    "Jumpstart": 6,
    "Overwatch": 7,
    "Aurora": 8,
    "Corona": 9,
    #"UltimatePrimary": 10,
    "Flashbang": 11,
    "Hailstorm": 12,
    "Knockdown": 15,
    "Airburst": 16,
    "Slapshot": 17,
    "Lock-on": 18,
    "Watchdog": 19,
    "Claymore": 20,
    "Lookout": 21,
    "Twister": 22,
    #"UltimateR1": 23,
    "Shockpunch": 24,
    "Slipstream": 25,
    #"UltimateGlide": 26,
    "Discord": 27,
    "Safeguard": 28,
    "Bulletproof": 29,
    "Stronghold": 30,
    "Highgear": 31,
    "Smackdown": 33,
    "Shieldwall": 34,
    "Hawkeye": 35,
    "Deflector": 36,
    "Fullspeed": 37,
    "Pressurepoint": 38,
    "Shepherd": 39,
    "Rangefinder": 40,
    "Kickback": 41,
    "Covert": 42,
    "Tractor": 43,
    #"UltimateShield": 44,
    "Buildup": 45,
    "Comeback": 46,
    "Highjump": 47,
    "Failsafe": 48,
    
    #Adding 50 for the Datacons, not sure if this order is correct or not, but what I am doing for now
    "Datacon (None)": 51,
    "Datacon (CharacterEnergon)": 52,
    "Datacon (RendersAutobots2)": 53,
    "Datacon (CardArtwork)": 54,
    "Datacon (DecepticloneSubmission)": 55,
    "Datacon (LeClezio1)": 56,
    "Datacon (RendersDecepticons2)": 57,
    "Datacon (ConceptArtDecepticlone)": 58,
    "Datacon (LeClezio2)": 59,
    "Datacon (TVSeriesThemeMusic)": 60,
    "Datacon (LevelStoryboardsAmazon)": 61,
    "Datacon (ArtPostcards)": 62,
    "Datacon (InstructionSheetOptimus)": 63,
    "Datacon (ConceptArtAutobots)": 64,
    "Datacon (MovieStills6)": 65,
    "Datacon (MovieStills7)": 66,
    "Datacon (RendersDecepticon)": 67,
    "Datacon (ThemeRegurgitator)": 68,
    "Datacon (MiniComic1)": 69,
    "Datacon (MiniComic2)": 70,
    "Datacon (MiniComic3)": 71,
    "Datacon (MiniComic4)": 72,
    "Datacon (ProductionArtAmazon)": 73,
    "Datacon (ProductionArtAntarctica)": 74,
    "Datacon (ProductionArtDeepAmazon)": 75,
    "Datacon (ProductionArtMidAtlantic)": 76,
    "Datacon (ProductionArtAlaska)": 77,
    "Datacon (ProductionArtStarship)": 78,
    "Datacon (ProdcutionArtPacificIsland)": 79,
    "Datacon (ProductionArtAutobotHQ)": 80,
    "Datacon (RendersAutobots)": 81,
    "Datacon (RendersDecepticlone)": 82,
    "Datacon (RendersMiniCons)": 83,
    "Datacon (ToyProductionHotShot)": 84,
    "Datacon (ToyProductionOptimus)": 85,
    "Datacon (ToyProductionRedAlert)": 86,
    "Datacon (ToyProductionMinicons)": 87,
    "Datacon (ToyProductionCyclonus)": 88,
    "Datacon (ToyProductionStarscream)": 89,
    "Datacon (ToyProductionTidalWave)": 90,
    "Datacon (ToyProductionMegatron)": 91,
    "Datacon (RendersAutobots3)": 92,
    "Datacon (CGProductionSequence2)": 93,
    "Datacon (CGProductionSequence)": 94,
    "Datacon (InstructionSheetMegatron)": 95,
    "Datacon (InstructionSheetHotShot)": 96,
    "Datacon (RendersDecepticlone2)": 97,
    "Datacon (RendersDecepticlone3)": 98,
    "Datacon (RendersDecepticlone4)": 99,
    "Datacon (TVSpot1)": 100,
    "Datacon (TVSpot2)": 101,
    "Datacon (TVSpot3)": 102,
    "Datacon (TVSpot4)": 103,
    "Datacon (TVSpot5)": 104,
    "Datacon (InstructionSheetRedAlert)": 105,
    "Datacon (MovieStills1)": 106,
    "Datacon (MovieStills2)": 107,
    "Datacon (MovieStills3)": 108,
    "Datacon (MovieStills4)": 109,
    "Datacon (MovieStills5)": 110,
    "Datacon (Dropbox_Wishbone)": 111,
    "Datacon (ThemeDropbox)": 112,
    "Datacon (LaunchPhotos)": 113,
    "Datacon (ThemeOrchestral)": 114,
    
    #saw this on the pickup list, I assume this is the powerlink
    #"Melee Damage Enhance": 150,
    
    #adding this per a requirement in the world.py
    "Health Drop": 151,
    "Big Head (2min)": 152,
    "Stealth Trap": 153,
    
    #Level Unlocks
    "Amazon Level Unlock": 160,
    "Antartica Level Unlock": 161,
    "Deep Amazon Level Unlock": 162,
    "Mid Atlantic Level Unlock": 163,
    "Alaska Level Unlock": 164,
    "Starship Level Unlock": 165,
    "Pacific Island Level Unlock": 166,
    "Unicron Unlock": 167
}



# Every location must have a unique integer ID associated with it.
# We will have a lookup from location name to ID here that, in world.py, we will import and bind to the world class.
# Even if a location doesn't exist on specific options, it must be present in this lookup.

#location ids are the Location Indexes
LOCATION_NAME_TO_ID: dict[str,int] = {
        "Amazon-Claymore Cave": 1,
    "Amazon-Spire": 2,
    "Amazon-Neighboring Mountain": 3,
    "Amazon-Ravine Cliff Cave": 4,
    "Amazon-Pressurepoint's Corner": 5,
    "Amazon-Foot of the Mountain": 6,
    "Amazon-Mountain Ruins": 7,
    "Amazon-Before the Waterfall Bridge": 8,
    "Amazon-Spidertank Triplets": 9,
    "Amazon-Ruined Temple Alcove": 10,
    "Amazon-Forest before the Bridge": 11,
    "Amazon-Ruined Temple Ledge": 12,
    "Amazon-Forest before Firefight": 13,
    "Amazon-Tutorial Minicon": 14,
    "Amazon-Ruined Temple Courtyard": 15,
    "Amazon-Light Unit Party": 16,
    "Amazon-Hidden Cave": 17,
    "Amazon-Riverside Ledge": 18,
    "Amazon-Waterfall Base": 19,
    "Amazon-Forest after the Bridge": 20,
    "Amazon-Surprise": 21,
    "Amazon-Forgettable Location": 22,
    "Amazon-Medium Unit Party": 23,
    "Amazon-Forest Across from the Basin 1": 24,
    "Amazon-Forest Across from the Basin 2": 25,
    "Antartica-Rock of Power": 1026,
    "Antartica-Research Base Office 1": 1027,
    "Antartica-Midfield Beacon": 1028,
    "Antartica-Hide-and-Seek Champion": 1029,
    "Antartica-Research Base Containers 1": 1030,
    "Antartica-Research Base Containers 2": 1031,
    "Antartica-Research Base Office 3": 1032,
    "Antartica-Crashed Icebreaker": 1033,
    "Antartica-Research Center Hangar": 1034,
    "Antartica-Beachfront Property": 1035,
    "Antartica-Crashed Plane": 1036,
    "Antartica-Research Base Office 4": 1037,
    "Antartica-Crevasse Field Overlook": 1038,
    "Antartica-Lonely Island": 1039,
    "Antartica-Research Base Office 2": 1040,
    "Antartica-Across the Field": 1041,
    "Deep Amazon-Island Altar": 2042,
    "Deep Amazon-Top of the Temple": 2043,
    "Deep Amazon-Spawn Ledge": 2044,
    "Deep Amazon-Waterfall Rock": 2045,
    "Deep Amazon-Jungle Ruins": 2046,
    "Deep Amazon-Patrolling Dropship": 2047,
    "Deep Amazon-Jungle Village Outskirts": 2048,
    "Deep Amazon-Field before the Bridge": 2049,
    "Deep Amazon-Temple Climb": 2050,
    "Deep Amazon-Mid-Jungle Ditch": 2051,
    "Deep Amazon-Village at the Foot of the Hill": 2052,
    "Deep Amazon-Jungle Village Warpgate": 2053,
    "Deep Amazon-Temple Dead End": 2054,
    "Deep Amazon-Temple Pool": 2055,
    "Deep Amazon-Temple Side-Path": 2056,
    "Deep Amazon-Forest before the Bridge": 2057,
    "Deep Amazon-Antechamber": 2058,
    "Deep Amazon-Antechamber Alcove": 2059,
    "Deep Amazon-Behind the Temple": 2060,
    "Mid Atlantic-Vanilla Progression": 3061,
    "Mid Atlantic-Distant Island": 3062,
    "Mid Atlantic-Pinnacle Rock": 3063,
    "Mid Atlantic-Atoll": 3064,
    "Alaska-Mountaintop": 4069,
    "Alaska-Small Forest": 4070,
    "Alaska-Cave's Far Ledge": 4071,
    "Alaska-Cave's Right Fork": 4072,
    "Alaska-Cave's Left Fork": 4073,
    "Alaska-Cave's Pool": 4074,
    "Alaska-Along the Canyon": 4075,
    "Alaska-Ocean Overlook": 4076,
    "Alaska-Hidden Hill": 4077,
    "Alaska-Canyon Clearing Ledge 1": 4078,
    "Alaska-Battlefield": 4079,
    "Alaska-Canyon Clearing Ledge 2": 4080,
    "Alaska-Dropship Island": 4081,
    "Alaska-Peninsula": 4082,
    "Alaska-Escape": 4083,
    "Alaska-Hillside": 4084,
    "Starship-Start of the Climb": 5085,
    "Starship-First Steps": 5086,
    "Starship-Main Elevator": 5087,
    "Starship-Sideways Elevator": 5088,
    "Starship-Lower Dropship": 5089,
    "Starship-Bait": 5090,
    "Starship-Free Space": 5091,
    "Starship-Across the Gap": 5092,
    "Starship-Early Gift": 5093,
    "Starship-Bridge": 5094,
    "Starship-Top of the Crashed Ship": 5096,
    "Starship-Dropdown 1": 5097,
    "Starship-Risky Jump": 5098,
    "Starship-Rock 1": 5099,
    "Starship-Middle Dropship": 5100,
    "Starship-Dropdown 2": 5101,
    "Starship-Rock 2": 5102,
    "Starship-Rock 3": 5103,
    "Starship-Rock 4": 5104,
    "Pacific Island-Small Silo": 6105,
    "Pacific Island-Moai": 6106,
    "Pacific Island-Back of the Volcano": 6107,
    "Pacific Island-Volcano Path": 6108,
    "Pacific Island-Lighthouse": 6109,
    "Pacific Island-Waterfall Climb": 6110,
    "Pacific Island-Stronghold Ledge": 6111,
    "Pacific Island-High Volcano Ledge": 6112,
    "Pacific Island-Forest Basin": 6113,
    "Pacific Island-Hidden Ledge": 6114,
    "Pacific Island-Above the Waterfall": 6115,
    "Pacific Island-Large Silo": 6116,
    "Pacific Island-Small Island": 6117,
    "Pacific Island-Bunker 1": 6118,
    "Pacific Island-Bunker 4": 6119,
    "Pacific Island-Bunker 5": 6120,
    "Pacific Island-Bunker 6": 6121,
    "Pacific Island-Bunker 7": 6122,
    "Pacific Island-Bunker 8": 6123,
    "Pacific Island-Bunker 9": 6124,
    "Pacific Island-Bunker 2": 6125,
    "Pacific Island-Bunker 3": 6126,
    "Amazon Beginner Weapon": 42069,
    
    #Boss Defeats
    "Amazon Boss": 200,
    "Antartica Boss": 201,
    "Deep Amazon Boss": 202,
    "Mid Atlantic Boss": 203,
    "Alaska Complete": 204,
    "Starship Boss": 205,
    "Pacific Island Boss": 206
}


#Original location (name) : linked location's ID
Linked_Locations = {
    "Mid Atlantic-Vanilla Progression": 3065,
    "Mid Atlantic-Distant Island": 3066,
    "Mid Atlantic-Pinnacle Rock": 3068,
    "Mid Atlantic-Atoll": 3067,
    "Starship-Bridge": 5095,
}


#adds 3 when outputing the file, so minicon ID is actually 16
Archipelago_Item_ID = 13


Minicons = [
    #"Blaster",
    "Skirmish",
    "Firefight",
    "Aftershock",
    "Sparkjump",
    "Jumpstart",
    "Overwatch",
    "Aurora",
    "Corona",
    #"UltimatePrimary",
    "Flashbang",
    "Hailstorm",
    "Knockdown",
    "Airburst",
    "Slapshot",
    "Lock-on",
    "Watchdog",
    "Claymore",
    "Lookout",
    "Twister",
    #"UltimateR1",
    "Shockpunch",
    "Slipstream",
    #"UltimateGlide",
    "Discord",
    "Safeguard",
    "Bulletproof",
    "Stronghold",
    "Highgear",
    "Smackdown",
    "Shieldwall",
    "Hawkeye",
    "Deflector",
    "Fullspeed",
    "Pressurepoint",
    "Shepherd",
    "Rangefinder",
    "Kickback",
    "Covert",
    "Tractor",
    #"UltimateShield"
    "Buildup",
    "Comeback",
    "Highjump",
    "Failsafe"
]


Explosive_Minicons = {
    "Claymore",
    "Failsafe",
    "Flashbang",
    "Hailstorm",
    "Lock-on",
    "Watchdog",
    "Slapshot"
}



Explosive_Locations = [
    "Antartica-Research Base Office 1",
    "Antartica-Research Base Containers 1",
    "Antartica-Research Base Containers 2",
    "Antartica-Research Base Office 3",
    "Antartica-Research Base Office 4",
    "Antartica-Research Base Office 2"
]

Slipstream_Locations = [
    "Amazon-Spire",
    "Amazon-Neighboring Mountain",
    "Amazon-Ravine Cliff Cave",
    "Amazon-Surprise",
    "Amazon-Forgettable Location",
    "Amazon-Medium Unit Party",
    "Amazon-Forest Across from the Basin 1",
    "Amazon-Forest Across from the Basin 2",
    "Antartica-Midfield Beacon",
    "Antartica-Lonely Island",
    "Deep Amazon-Island Altar",
    "Deep Amazon-Spawn Ledge",
    "Deep Amazon-Waterfall Rock",
    "Deep Amazon-Patrolling Dropship",
    "Mid Atlantic-Distant Island",
    "Alaska-Along the Canyon",
    "Pacific Island-Moai",
    "Pacific Island-Back of the Volcano",
    "Pacific Island-Volcano Path",
    "Pacific Island-Lighthouse",
    "Pacific Island-Waterfall Climb",
    "Pacific Island-Stronghold Ledge",
    "Pacific Island-High Volcano Ledge",
    "Pacific Island-Hidden Ledge",
    "Pacific Island-Above the Waterfall",
    "Pacific Island-Small Island",
    "Pacific Island-Bunker 1",
    "Pacific Island-Bunker 4",
    "Pacific Island-Bunker 5",
    "Pacific Island-Bunker 6",
    "Pacific Island-Bunker 7",
    "Pacific Island-Bunker 8",
    "Pacific Island-Bunker 9",
    "Pacific Island-Bunker 2",
    "Pacific Island-Bunker 3",
    "Pacific Island Boss"
]

Slipstream_Explosive = [
    "Pacific Island-Small Silo",
    "Pacific Island-Large Silo"
]

Highjump_Locations = [
    "Antartica-Rock of Power",
    "Deep Amazon-Temple Pool",
    "Deep Amazon-Antechamber Alcove",
    "Alaska-Mountaintop",
    "Alaska-Cave's Right Fork",
    "Alaska-Cave's Left Fork",
    "Alaska-Cave's Pool",
    "Alaska-Escape",
    "Starship-Start of the Climb",
    "Starship-First Steps",
    "Starship-Main Elevator",
    "Starship-Sideways Elevator",
    "Starship-Lower Dropship",
    "Starship-Bait",
    "Starship-Free Space",
    "Starship-Across the Gap",
    "Starship-Early Gift",
    "Starship-Bridge",
    "Starship-Top of the Crashed Ship",
    "Starship-Dropdown 1",
    "Starship-Risky Jump",
    "Starship-Middle Dropship",
    "Starship-Dropdown 2",
    "Starship Boss",
    "Alaska Complete"
]

Slipstream_Highjump = [
    "Amazon-Spidertank Triplets",
    "Starship-Rock 1",
    "Starship-Rock 2",
    "Starship-Rock 3",
    "Starship-Rock 4",
    "Alaska-Cave's Far Ledge"
]